spring.application.name=JWT_Implementation

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/jwt_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true